---
# tasks file for server
- name: Update apt cache
  become: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Install required software
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - mysql-server
    - php7.2
    - libapache2-mod-php7.2
    - php7.2-mysql
    - python-mysqldb
